### ISSUE TITLE
cloud-init version

### ISSUE THREAD

**Issue by mateuszdrab** [BlueKrypto/k3os#6]
Hey @BlueKrypto 

Thanks for maintaining the fork of K3os.

I was just playing around with it, trying to see if it would be suitable for my scenario and I tried to provision a node via cloud-init on VMware, it did not work so I'm wondering which version of cloud-init is included in the distro. 
I couldn't find it.

Can you let me know?

I tried launching `/etc/sbin/metadata` and it was not able to determine the metadata from the VM's `userdata` and `metadata` fields.

I think the data source is new, merged last year... https://github.com/canonical/cloud-init/pull/953

Thanks

**Comment by BlueKrypto** [comment]
@mateuszdrab Thank you for opening this issue; I will add clarity to the documentation because I know others have asked about this when it was a rancher project.

k3OS does not use cloud-init, it uses the cloud-init like functionality from linuxkit's [metadata package](https://github.com/linuxkit/linuxkit/tree/master/pkg/metadata). There is an issue on the original project repo [here](https://github.com/rancher/k3os/issues/413)

I am not sure if it's feasible at this point in the project to change to the actual cloud-init project, but I am willing to research it.

There is also the [packer](https://github.com/BlueKrypto/k3os/tree/master/package/packer/vsphere) portion of the repository, which might help you.

**Comment by mateuszdrab** [comment]
Hi @BlueKrypto 

Thanks for clarifying. I didn't realize there was another solution, but it makes sense now.

I'm aware of the packer solution, but I was hoping to explore setting clusterapi to deploy nodes to my already existing cluster and for that I wanted to utilize cloud-init as it is the only way for clusterapi to provide data to provisioned VMs. Based on the documentation of clusterapi, I should be able to provide custom cloud-init config, overriding the need to use a kubadm equipped image and I think k3os would work.

Based on the sentence in the `Configuration` section of the project's read me - I thought cloud-init was supported.

> All configuration is done through a single cloud-init style config file that is either packaged in the image, downloaded though cloud-init or managed by Kubernetes. The configuration file is found at...

I'm not sure if the `metadata` component is even in use... I guess I could use it to provision the k3os config file from 'cd-rom' or any of the supported providers. Looks like support for vSphere is in no luck state https://github.com/linuxkit/linuxkit/pull/3526 and https://github.com/rancher/k3os/issues/413#issuecomment-971993752 confirm it.

Cloud-init switch would be the most viable - but I'm not sure of the complexity. The only thing we'd need from cloud-init to work is a reliable way to deliver the k3os config file.

If it's not viable, I think I'll just go with a plain Ubuntu approach which is what Rancher deploys when creating my RKE2 cluster.

**Comment by BlueKrypto** [comment]
@mateuszdrab When I ran a vmware solution with k3OS, I kept an ISO I had configured to have a pre-populated command in the grub loader that caused it to automatically use a cd-rom for the init config. Then I created an ISO with the config needed and loaded it with the vm.

**Comment by mateuszdrab** [comment]
> @mateuszdrab When I ran a vmware solution with k3OS, I kept an ISO I had configured to have a pre-populated command in the grub loader that caused it to automatically use a cd-rom for the init config. Then I created an ISO with the config needed and loaded it with the vm.

That would be an option if I could mount an iso through cluster API...
Anyways, I think I'll leave this project for now since it's not that urgent. I already got some provisioning playbooks in Ansible and I think of making that more usable so that it can add VMs as well as configuring it... 
I just thought it would be nice to explore the cluster API deployment but there are other ways to achieve my objective 😄
